#! /bin/sh

cd `dirname $0`
./patch_zfs_mount_with_local_file_system $@
patch $@ -p0 -i devd_init_script_includes_usr_bin_in_path.diff
./patch_devd_starts_after_networking $@
patch $@ -p0 -i boot_no_remount_errors.diff
cd - > /dev/null

