# /etc/zsh/zshenv
# 
# Configuration file for zsh
# 
# Originally taken from files available at 
# http://formation-debian.via.ecp.fr/fichiers-config.tar.gz
# which are part of the "Formation Debian GNU/Linux".
# 
# Modified by Joel Lopes Da Silva.

# PATH & MANPATH
export PATH="/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/sbin:/sbin:/usr/games"
[[ -x "$HOME/bin" ]] && export PATH="$PATH:$HOME/bin"

# Default viewer and editor (for Crontab, CVS, ...)
export VISUAL=vim
export EDITOR=vim

# Permissions rw-r--r-- for created files
# and rwxr-xr-x for created directories
umask 022

# HTTP/FTP Proxy without password
#export http_proxy="http://proxy.exemple.org:8080"
#export ftp_proxy="ftp://proxy.exemple.org:8080"

# HTTP/FTP Proxy with password
#export http_proxy="http://login:password@proxy.exemple.org:8080"
#export ftp_proxy="ftp://login:password@proxy.exemple.org:8080"

# Don't use the proxy for local domains
#export no_proxy="exemple.org"

# Use color for grep
export GREP_OPTIONS='--color=auto'

